import { getAppConfig } from './app-config';

// ── Email template helpers ──────────────────────────────────────────────────

function escapeHtml(str: string): string {
    return str
        .replace(/&/g, '&amp;')
        .replace(/</g, '&lt;')
        .replace(/>/g, '&gt;')
        .replace(/"/g, '&quot;');
}

function sectionHeading(title: string): string {
    return `<h2 style="font-size:10px;letter-spacing:0.25em;text-transform:uppercase;color:#d4a843;margin:0 0 8px 0;font-family:-apple-system,Helvetica,Arial,sans-serif;font-weight:600;">${escapeHtml(title)}</h2>`;
}

function sectionParagraph(text: string): string {
    return `<p style="font-size:14px;color:#b8b0a0;line-height:1.6;margin:0;">${escapeHtml(text)}</p>`;
}

function sectionBlock(title: string, content: string): string {
    return `<div style="margin-bottom:20px;">${sectionHeading(title)}${content}</div>`;
}

function textSection(title: string, text: string): string {
    return sectionBlock(title, sectionParagraph(text));
}

function bulletSection(title: string, items: string[]): string {
    const bullets = items.map(item =>
        `<table cellpadding="0" cellspacing="0" border="0" style="margin-bottom:6px;"><tr><td style="vertical-align:top;padding-right:8px;color:#d4a843;font-size:14px;font-family:Georgia,serif;">--</td><td style="font-size:14px;color:#b8b0a0;line-height:1.6;font-family:Georgia,serif;">${escapeHtml(item)}</td></tr></table>`
    ).join('');
    return sectionBlock(title, bullets);
}

function wrapEmail(headline: string, sections: string): string {
    return `<table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="margin:0;padding:0;font-family:Georgia,'Times New Roman',serif;">
<tr>
<td align="center" style="padding:0;">
<table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="max-width:100%;background-color:#141414;border:1px solid rgba(212,168,67,0.2);border-radius:12px;">
<tr>
<td style="padding:32px;">
<div style="text-align:center;margin-bottom:24px;">
<span style="font-size:14px;letter-spacing:0.2em;color:#d4a843;text-transform:uppercase;font-family:-apple-system,Helvetica,Arial,sans-serif;">Athena</span>
</div>
<h1 style="font-size:20px;color:#e8e0d0;font-weight:400;line-height:1.4;margin:0 0 24px 0;font-family:Georgia,serif;">${escapeHtml(headline)}</h1>
${sections}
<div style="border-top:1px solid rgba(212,168,67,0.1);padding-top:16px;margin-top:24px;text-align:center;">
<span style="font-size:11px;color:#666;font-family:-apple-system,Helvetica,Arial,sans-serif;">Generated by Athena</span>
</div>
</td>
</tr>
</table>
</td>
</tr>
</table>`;
}

// ── Send notification ───────────────────────────────────────────────────────

export async function sendReportNotification(subject: string, html: string, text: string) {
    const apiKey = await getAppConfig('RESEND_API_KEY');
    const email = await getAppConfig('NOTIFICATION_EMAIL');

    if (!apiKey || !email) return; // Notifications not configured, skip silently

    try {
        await fetch('https://api.resend.com/emails', {
            method: 'POST',
            headers: {
                'Authorization': `Bearer ${apiKey}`,
                'Content-Type': 'application/json',
            },
            body: JSON.stringify({
                from: 'Athena <onboarding@resend.dev>',
                to: email,
                subject,
                html,
                text,
            }),
        });
    } catch (err) {
        console.error('[Notifications] Failed to send email:', err);
    }
}

// ── Formatters ──────────────────────────────────────────────────────────────

export function formatDailyReport(report: any): { subject: string; html: string; text: string } {
    const r = report.report || report;
    const headline = r.headline || 'Daily Update';
    const subject = `Morning Briefing: ${headline}`;

    // HTML
    const htmlSections = [
        r.readiness && textSection('Readiness', r.readiness),
        r.habitNote && textSection('Habits', r.habitNote),
        r.trainingRec && textSection('Training', r.trainingRec),
        r.reading && textSection('Reading', r.reading),
        r.projectTasks?.length && bulletSection('Projects', r.projectTasks),
        r.focusItems?.length && bulletSection("Today's Focus", r.focusItems),
        r.insight && textSection('Insight', r.insight),
    ].filter(Boolean).join('');
    const html = wrapEmail(headline, htmlSections);

    // Plain text fallback
    const textSections = [
        r.readiness && `READINESS\n${r.readiness}`,
        r.habitNote && `HABITS\n${r.habitNote}`,
        r.trainingRec && `TRAINING\n${r.trainingRec}`,
        r.reading && `READING\n${r.reading}`,
        r.projectTasks?.length && `PROJECTS\n${r.projectTasks.map((i: string) => `- ${i}`).join('\n')}`,
        r.focusItems?.length && `TODAY'S FOCUS\n${r.focusItems.map((i: string) => `- ${i}`).join('\n')}`,
        r.insight && `INSIGHT\n${r.insight}`,
    ].filter(Boolean).join('\n\n');
    const text = textSections || 'Your daily briefing is ready in Athena.';

    return { subject, html, text };
}

export function formatWeeklyReport(report: any): { subject: string; html: string; text: string } {
    const r = report.report || report;
    const headline = r.headline || 'Weekly Update';
    const subject = `Weekly Review: ${headline}`;

    // HTML
    const htmlSections = [
        r.health?.length && bulletSection('Health', r.health),
        r.habits?.length && bulletSection('Habits', r.habits),
        r.training?.length && bulletSection('Training', r.training),
        r.coachRecap && textSection('Coach Recap', r.coachRecap),
        r.projects?.length && bulletSection('Projects', r.projects),
        r.insights?.length && bulletSection('Insights', r.insights),
        r.thisWeekSplit && textSection('Training Split', r.thisWeekSplit),
        r.thisWeek?.length && bulletSection('This Week', r.thisWeek),
    ].filter(Boolean).join('');
    const html = wrapEmail(headline, htmlSections);

    // Plain text fallback
    const textSections = [
        r.health?.length && `HEALTH\n${r.health.map((i: string) => `- ${i}`).join('\n')}`,
        r.habits?.length && `HABITS\n${r.habits.map((i: string) => `- ${i}`).join('\n')}`,
        r.training?.length && `TRAINING\n${r.training.map((i: string) => `- ${i}`).join('\n')}`,
        r.coachRecap && `COACH RECAP\n${r.coachRecap}`,
        r.projects?.length && `PROJECTS\n${r.projects.map((i: string) => `- ${i}`).join('\n')}`,
        r.thisWeek?.length && `THIS WEEK\n${r.thisWeek.map((i: string) => `- ${i}`).join('\n')}`,
    ].filter(Boolean).join('\n\n');
    const text = textSections || 'Your weekly review is ready in Athena.';

    return { subject, html, text };
}

export function formatMonthlyReport(report: any): { subject: string; html: string; text: string } {
    const r = report.report || report;
    const headline = r.headline || 'Monthly Update';
    const subject = `Monthly Review: ${headline}`;

    // HTML
    const htmlSections = [
        r.narrative && textSection('Narrative', r.narrative),
        r.health?.length && bulletSection('Health', r.health),
        r.habits?.length && bulletSection('Habits', r.habits),
        r.training?.length && bulletSection('Training', r.training),
        r.trainingProgression?.length && bulletSection('Strength Progression', r.trainingProgression),
        r.patterns?.length && bulletSection('Patterns', r.patterns),
        r.thisMonth?.length && bulletSection('This Month', r.thisMonth),
    ].filter(Boolean).join('');
    const html = wrapEmail(headline, htmlSections);

    // Plain text fallback
    const textSections = [
        r.narrative && `NARRATIVE\n${r.narrative}`,
        r.health?.length && `HEALTH\n${r.health.map((i: string) => `- ${i}`).join('\n')}`,
        r.habits?.length && `HABITS\n${r.habits.map((i: string) => `- ${i}`).join('\n')}`,
        r.training?.length && `TRAINING\n${r.training.map((i: string) => `- ${i}`).join('\n')}`,
        r.trainingProgression?.length && `STRENGTH PROGRESSION\n${r.trainingProgression.map((i: string) => `- ${i}`).join('\n')}`,
        r.patterns?.length && `PATTERNS\n${r.patterns.map((i: string) => `- ${i}`).join('\n')}`,
        r.thisMonth?.length && `THIS MONTH\n${r.thisMonth.map((i: string) => `- ${i}`).join('\n')}`,
    ].filter(Boolean).join('\n\n');
    const text = textSections || 'Your monthly review is ready in Athena.';

    return { subject, html, text };
}

export function formatCoachNotes(workoutType: string, notes: any): { subject: string; html: string; text: string } {
    const subject = `Workout Coach: ${workoutType}`;
    const notesList: string[] = Array.isArray(notes?.notes) ? notes.notes : Array.isArray(notes) ? notes : [];
    const warnings: string[] = Array.isArray(notes?.warnings) ? notes.warnings.filter(Boolean) : [];
    const weightNotes: Record<string, string> = notes?.weightNotes || notes?.weight_notes || {};
    const exerciseOrder: string[] = notes?.exerciseOrder || notes?.exercise_order || [];

    // HTML
    let htmlSections = '';

    if (notesList.length > 0) {
        // First note is recovery assessment
        htmlSections += textSection('Recovery', notesList[0]);
        if (notesList.length > 1) {
            htmlSections += bulletSection('Strategy', notesList.slice(1));
        }
    }

    if (Object.keys(weightNotes).length > 0) {
        const orderedExercises = exerciseOrder.length > 0
            ? exerciseOrder.filter(e => weightNotes[e])
            : Object.keys(weightNotes);
        const exerciseItems = orderedExercises.map(e => `${e}: ${weightNotes[e]}`);
        htmlSections += bulletSection('Exercises', exerciseItems);
    }

    if (warnings.length > 0) {
        htmlSections += sectionBlock('Warning', `<p style="font-size:14px;color:#f87171;line-height:1.6;margin:0;">${escapeHtml(warnings[0])}</p>`);
    }

    const html = wrapEmail(`${workoutType} -- Pre-Workout`, htmlSections || sectionParagraph('Your pre-workout coach notes are ready in Athena.'));

    // Plain text fallback
    const textParts = [
        notesList.length > 0 && `COACH NOTES\n${notesList.join('\n')}`,
        Object.keys(weightNotes).length > 0 && `EXERCISES\n${(exerciseOrder.length > 0 ? exerciseOrder.filter(e => weightNotes[e]) : Object.keys(weightNotes)).map(e => `- ${e}: ${weightNotes[e]}`).join('\n')}`,
        warnings.length > 0 && `WARNING: ${warnings[0]}`,
    ].filter(Boolean).join('\n\n');
    const text = textParts || 'Your pre-workout coach notes are ready in Athena.';

    return { subject, html, text };
}
