export interface Quote {
    text: string;
    author: string;
}

export const QUOTES: Quote[] = [
    // Original Quotes
    { text: "It's better to be overprepared and underwhelmed than it is to be underprepared and overwhelmed.", author: "Dylan Greynolds" },
    { text: "If you wanna kill a big dream, tell it to a small-minded person.", author: "Steve Harvey" },
    { text: "Don't fall back on anything, fall forwards and you'll at least see what you're going to hit.", author: "Denzel Washington" },
    { text: "Don't confuse momentum with progress. Just because you're doing a lot more doesn't mean you're getting a lot more done.", author: "Denzel Washington" },
    { text: "If you always do what you always did, you'll always get what you always got.", author: "Henry Ford" },
    { text: "If I cannot do great things, I can do small things in a great way.", author: "Napoleon Hill" },
    { text: "You'll never see a hater doing better than you", author: "David Goggins" },
    { text: "Day by day, what you choose, what you think, and what you do is who you become.", author: "Heraclitus" },
    { text: "You don't make progress if you're always raising the bar.", author: "Unknown" },
    { text: "The best time to plant a tree was 20 years ago. The second best time is now.", author: "Unknown" },
    { text: "Do not wait to strike till the iron is hot, but make it hot by striking.", author: "William Butler Yeats" },
    { text: "You can't be normal and expect abnormal returns.", author: "Jeff Bezos" },
    { text: "A man who fears suffering is already suffering from what he fears.", author: "Michel de Montaigne" },
    { text: "Better to be a warrior in a garden, than a gardener in a war.", author: "Chinese Proverb" },
    { text: "Today is difficult, tomorrow is much more difficult, but the day after tomorrow is beautiful. Most people die tomorrow evening.", author: "Jack Ma" },
    { text: "Compare yourself to who you were yesterday, not to who someone else is today.", author: "Jordan Peterson" },
    { text: "It's better to fail in originality than to succeed in imitation.", author: "Herman Melville" },
    { text: "Never fear a storm, learn to dance in the rain.", author: "Gordon Ramsay" },
    { text: "May you always remember to enjoy the road, especially when it's a hard one.", author: "Kobe Bryant" },
    { text: "People want you to do well, but not better than them.", author: "Alex Hormozi" },
    { text: "If you only have 24 hours in a day, your success is dependent upon how you spend those 24.", author: "Eric Thomas" },
    { text: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt" },
    { text: "Believe you can and you're halfway there.", author: "Theodore Roosevelt" },
    { text: "The only limit to our realization of tomorrow is our doubts of today.", author: "Franklin D. Roosevelt" },
    { text: "We suffer more often in imagination than in reality.", author: "Seneca" },
    { text: "The best way to predict the future is to invent it.", author: "Alan Kay" },
    { text: "Simplicity is the ultimate sophistication.", author: "Leonardo da Vinci" },
    { text: "Your time is limited, so don't waste it living someone else's life.", author: "Steve Jobs" },
    { text: "Waste no more time arguing about what a good man should be. Be one.", author: "Marcus Aurelius" },
    { text: "If you want to go fast, go alone. If you want to go far, go together.", author: "African Proverb" },
    { text: "A little rain each day fills the rivers to overflowing.", author: "Malagasy Proverb" },
    { text: "The one who asks questions doesn't lose his way.", author: "Swahili Proverb" },
    { text: "A fault confessed is half redressed.", author: "Zulu Proverb" },
    { text: "However long the night, the dawn will break.", author: "African Proverb" },
    { text: "It is better to light a candle than curse the darkness.", author: "Chinese Proverb" },
    { text: "Fall seven times, stand up eight.", author: "Japanese Proverb" },
    { text: "Vision without action is a daydream. Action without vision is a nightmare.", author: "Japanese Proverb" },
    { text: "A journey of a thousand miles begins with a single step.", author: "Lao Tzu" },
    { text: "The bamboo that bends is stronger than the oak that resists.", author: "Japanese Proverb" },
    { text: "When the winds of change blow, some people build walls and others build windmills.", author: "Chinese Proverb" },
    { text: "A gem cannot be polished without friction, nor a man perfected without trials.", author: "Chinese Proverb" },
    { text: "He who asks a question is a fool for five minutes; he who does not ask a question remains a fool forever.", author: "Chinese Proverb" },
    { text: "Better to see something once than hear about it a thousand times.", author: "Asian Proverb" },
    { text: "Shared joy is a double joy; shared sorrow is half a sorrow.", author: "Swedish Proverb" },
    { text: "The night rinses what the day has soaped.", author: "Swiss Proverb" },
    { text: "Age is honorable and youth is noble.", author: "Irish Proverb" },
    { text: "A spoon does not know the taste of soup, nor a learned fool the taste of wisdom.", author: "Welsh Proverb" },
    { text: "Even the smallest dog can lift its leg on the tallest building.", author: "Danish Proverb" },
    { text: "The best revenge is massive success.", author: "Italian saying" },
    { text: "To be willing is only half the task.", author: "Armenian Proverb" },
    { text: "When the sun rises, it rises for everyone.", author: "Cuban Proverb" },
    { text: "He who has health has hope, and he who has hope has everything.", author: "Arabic Proverb" },
    { text: "Patience is the key to paradise.", author: "Turkish Proverb" },
    { text: "We do not inherit the earth from our ancestors; we borrow it from our children.", author: "Native American Proverb" },
    { text: "Listen to the wind, it talks. Listen to the silence, it speaks. Listen to your heart, it knows.", author: "Native American Proverb" },
    { text: "Tell me and I'll forget. Show me, and I may not remember. Involve me, and I'll understand.", author: "Native American Proverb" },

    // Extended Quotes
    { text: "Doubt begins when you value their opinion more than your own.", author: "Unknown" },
    { text: "Embarrassment is an under-explored emotion, go out there and make a fool of yourself", author: "Austin Butler" },
    { text: "The only person you should try to be better than is the person you were yesterday.", author: "Unknown" },
    { text: "He who has a why to live can bear almost any how.", author: "Friedrich Nietzsche" },
    { text: "To different minds, the same world is a hell and a heaven.", author: "Ralph Waldo Emerson" },
    { text: "It is not death that a man should fear, but should fear never beginning to live.", author: "Marcus Aurelius" },
    { text: "He who dares not grasp the thorn, should never crave the rose.", author: "Anne Bronte" },
    { text: "A candle loses nothing by lighting another.", author: "James Keller" },
    { text: "The climb never ends, so learn to pause and enjoy the moment.", author: "Unknown" },
    { text: "What you think you become. What you feel you attract. What you imagine you create.", author: "Buddha" },
    { text: "Stop complaining about the results you didn't get from the work you didn't put in.", author: "Unknown" },
    { text: "Become the person who would attract the results you seek.", author: "Jim Cathcart" },
    { text: "I was chasing perfection and excellence even though I knew I would probably never catch it. But just the fact that I was willing to chase it, I would defeat most of my opponents because most of my opponents would never chase something that didn't have any guarantees attached to it.", author: "Kobe Bryant" },
    { text: "Better to shoot and miss than let time run out and wonder what if.", author: "Unknown" },
    { text: "The man who moves a mountain begins by carrying away small stones.", author: "Unknown" },
    { text: "The dream is free but the hustle is sold separately.", author: "Eric Thomas" },
    { text: "There are seats waiting for you at tables you haven't even seen yet.", author: "Unknown" },
    { text: "If you believe it will work out, you'll see opportunities. If you believe it won't work out, you'll see obstacles.", author: "Wayne Dyer" },
    { text: "You have within you right now, everything you need to deal with whatever the world can throw at you.", author: "Brian Tracy" },
    { text: "Direction is much more important than speed. A lot of people are going nowhere fast.", author: "Unknown" },
    { text: "To lead the orchestra, you have to turn your back on the crowd.", author: "Unknown" },
    { text: "A man who loves walking will walk further than the man who loves the destination.", author: "Unknown" },
    { text: "Don't be pushed by your problems. Be led by your dreams.", author: "Unknown" },
    { text: "Wages make you a living. Profits make you a fortune.", author: "Jim Rohn" },
    { text: "The cost of never taking a risk is spending the rest of your life wishing you had.", author: "Unknown" },
    { text: "I can't cry about having a lot on my plate when my goal was to eat.", author: "Steve Harvey" },
    { text: "What if it could turn out better than you imagined?", author: "Unknown" },
    { text: "You are what you do, not what you say you'll do.", author: "Carl Jung" },
    { text: "If you're not willing to sacrifice for your goals, that's okay. You just need to know that your goals will become the sacrifice.", author: "Unknown" },
    { text: "You are what you think about. Everything that you think about, you become. Thoughts lead to actions, actions lead to behaviors, behaviors lead to lifestyle, lifestyle determines your destiny.", author: "Earl Nightingale" },
    { text: "Any man can learn anything he will, but no man can teach except to those who want to learn.", author: "Henry Ford" },
    { text: "The man who graduates today and stops learning tomorrow is uneducated the day after.", author: "Newton D. Baker" },
    { text: "The bad news is time flies. The good news is you're the pilot.", author: "Michael Altshuler" },
    { text: "Set your mind on a definite goal and observe how quickly the world stands aside to let you pass.", author: "Napoleon Hill" },
    { text: "Bite off more than you can chew. You can figure out how to chew later.", author: "Unknown" },
    { text: "You don't learn to swim by reading about water.", author: "Unknown" },
    { text: "The master in the art of living makes little distinction between his work and his play, his labor and his leisure, his mind and his body, his information and his recreation, his love and his religion. He hardly knows which is which. He simply pursues his vision of excellence at whatever he does, leaving others to decide whether he is working or playing. To him he's always doing both.", author: "James A. Michener" },
    { text: "Every generation has its defining works. More than 300,000 people worked to put a man on the moon – including that janitor. Millions of volunteers immunized children around the world against polio. Millions of more people built the Hoover dam and other great projects. These projects didn't just provide purpose for the people doing those jobs, they gave our whole country a sense of pride that we could do great things. Now it's our turn to do great things. I know, you're probably thinking: I don't know how to build a dam, or get a million people involved in anything. But let me tell you a secret: no one does when they begin. Ideas don't come out fully formed. They only become clear as you work on them. You just have to get started. If I had to understand everything about connecting people before I began, I never would have started Facebook.", author: "Mark Zuckerberg" },
    { text: "Hate has four letters, but so does Love. Enemies has seven letters, but so does Friends. Lying has five letters, but so does Truth. Failure has seven letters, but so does Success. And Negativity has 10 letters, but so does Positivity. You always have a choice, so choose the better side of it.", author: "Tamara Kulish" },
    { text: "One day or day one", author: "Dwayne (The Rock) Johnson" },
    { text: "Nothing is ever going to be given to you. Everything is going to be earned. If you don't go out there and put in the work and effort... one you're not going to get the results and two you didn't deserve it, you didn't earn it.", author: "Tiger Woods" },
    { text: "If you want to live like few can, you have to do what few will.", author: "Unknown" },
    { text: "Don't watch the clock; do what it does. Keep going.", author: "Sam Levenson" },
    { text: "The sun rises every day, no matter how dark the night was.", author: "Unknown" },
    { text: "The tree bends so it does not break, but it carries the memory of every storm.", author: "Unknown" },
    { text: "It does not matter how slowly you go as long as you do not stop.", author: "Confucius" },
    { text: "Champions do daily what everyone else does occasionally.", author: "Inky Johnson" },
    { text: "Earn with your mind, not your time.", author: "Naval Ravikant" },
    { text: "We must suffer from one of two pains: the pain of discipline or the pain of regret.", author: "Jim Rohn" },
    { text: "Rest at the end, not in the middle.", author: "Kobe Bryant" },
    { text: "The life you want demands a price. Discomfort is the down payment. Consistency is the monthly fee. Are you willing to pay it?", author: "Unknown" },
    { text: "All roads that lead to success have to pass through hard work boulevard at some point.", author: "Eric Thomas" },
    { text: "A river cuts through rock, not because of its power, but because of its persistence.", author: "James N. Watkins" },
    { text: "You can't have a million-dollar dream with a minimum-wage work ethic.", author: "Unknown" },
    { text: "Hustle until your haters ask if you're hiring.", author: "Unknown" },
    { text: "Don't think about what can happen in a month. Don't think about what can happen in a year. Just focus on the 24 hours in front of you and do what you can to get closer to where you want to be.", author: "Eric Thomas" },
    { text: "Show me a man of average ability but extraordinary drive, and I will show you a winner every time.", author: "Andrew Carnegie" },
    { text: "Discipline is choosing between what you want now and what you want most.", author: "Unknown" },
    { text: "I've lost my mind doing this game. Like Vincent Van Gogh. He dedicated his life to his art and lost his mind in the process. That's happened to me. But fuck it. When that gold belt is around my waist, when my mother has a big mansion, my girlfriend has a different car for everyday of the week, my kid's kids have anything they ever want; then it will pay. Then I'll be happy; I lost my mind.", author: "Conor McGregor" },
    { text: "In all those very different contexts, one characteristic emerged as a significant predictor of success. And it wasn't social intelligence. It wasn't good looks, physical health, and it wasn't IQ. It was grit. Grit is passion and perseverance for very long-term goals. Grit is having stamina. Grit is sticking with your future, day in, day out, not just for the week, not just for the month, but for years, and working really hard to make that future a reality. Grit is living life like it's a marathon, not a sprint.", author: "Angela Lee Duckworth" },
    { text: "An inch of movement will bring you closer to your goal than a mile of intention.", author: "Steve Miraboli" },
    { text: "Be not afraid of growing slowly, be afraid only of standing still.", author: "Unknown" },
    { text: "If you stay in environments where people don't recognize the value of you, you will shrink your gift to the size of what they can stand.", author: "Keion" },
    { text: "When you're on the way up, everyone roots for you because you remind them of their dreams. When you're at the top, everyone tears you down because you remind them that they gave up on them.", author: "Alex Hormozi" },
    { text: "You can never cross the ocean until you have the courage to lose sight of the shore.", author: "Columbus" },
    { text: "Everything you thought was drowning you, actually taught you how to swim.", author: "Unknown" },
    { text: "A cat that dreams of becoming a lion must lose its appetite for rats.", author: "Unknown" },
    { text: "Better to do something imperfectly than do nothing flawlessly.", author: "Robert Schuller" },
    { text: "If you continue to believe as you have always believed...you will continue to act as you have always acted...you will continue to get what you have always gotten. If you want different results in your life, all you have to do is change your mind.", author: "Unknown" },
    { text: "If you spend your time chasing butterflies, they'll fly away. But if you spend time making a beautiful garden, the butterflies will come. Don't chase, attract.", author: "Unknown" },
    { text: "Don't be afraid to give up the good for the great.", author: "John Rockefeller" },
    { text: "You cannot hope to make progress in areas where you have taken no action.", author: "Unknown" },
    { text: "Change is uncomfortable, but nothing is as uncomfortable as staying stuck somewhere you don't belong.", author: "Unknown" },
    { text: "Opportunities only look like opportunities in the rear-view mirror; today they only look like risk.", author: "Unknown" },
    { text: "Success is not final, failure is not fatal: It is the courage to continue that counts.", author: "Winston Churchill" },
    { text: "You are never too old to set another goal or to dream a new dream.", author: "C.S. Lewis" },
    { text: "Ideas don't become fully formed at the start, they only become clear as you work on them. You just have to start.", author: "Naval Ravikant" },
    { text: "Most people do not listen with the intent to understand; they listen with the intent to reply.", author: "Stephen Covey" },
    { text: "Get comfortable with being uncomfortable.", author: "Jillian Michaels" },
    { text: "The quickest way to succeed is to start now and figure it out as you go. You can't learn to drive in a parked car.", author: "Unknown" },
    { text: "A comfort zone is a beautiful place, but nothing ever grows there.", author: "Unknown" },
    { text: "Continuous improvement is better than delayed perfection.", author: "Unknown" },
    { text: "Grow to become comfortable taking your best bad guess and aim to be directionally correct rather than searching for the perfect answer.", author: "Unknown" },
    { text: "I'm not comfortable with comfort. I'm only comfortable when I'm in a place where I'm constantly learning and growing.", author: "Unknown" },
    { text: "Let me fall if I must fall. The one I will become will catch me.", author: "Unknown" },
    { text: "Playing it safe is the riskiest strategy. The biggest regret of people on their deathbeds isn't failing-it's not having the courage to live authentically. Imagine spending 80 years on this planet, following a script someone else wrote for you, only to realize you were a supporting character in your own life. Fuck that. Go big. Take the risk. Chase the dream that keeps you up at night. If it fails, you've got a great story. But if it works? It changes everything. Regret stings more than failure ever will.", author: "Unknown" },
    { text: "Your job is not to figure out how it's going to happen for you, but to open the door in your head. And when the door opens in real life, just walk through it. And don't worry if you miss your cue because there's always doors opening. They keep opening. And when I say, Life doesn't happen to you, it happens for you. I really don't know if that's true. I'm just making a conscious choice to perceive challenges as something beneficial so that I can deal with them in the most productive way. You'll come up with your own style. That's part of the fun.", author: "Jim Carrey" },
    { text: "There is no passion to be found playing small and settling for a life that is less than the one you are capable of living.", author: "Nelson Mandela" },
    { text: "You can't give your life more time, so give the time you have left more life.", author: "Buddha" },
    { text: "A man without a vision for his future always returns to the past.", author: "Unknown" },
    { text: "You will get the most fulfillment in life from creating value. Creation requires optimism. You have to see the future world you want to live in and then spend the time, money, and energy to make it a reality.", author: "Unknown" },
    { text: "You can't hold onto the gift of the present if you are always chasing what the future will hold.", author: "Unknown" },
    { text: "Do not go where the path may lead, go instead where there is no path and leave a trail.", author: "Ralph Waldo Emerson" },
    { text: "Do not spoil what you have by desiring what you have not; remember that what you now have was once among the things you only hoped for.", author: "Epicurus" },
    { text: "What you get by achieving your goals is not as important as what you become by achieving your goals.", author: "Zig Ziglar" },
    { text: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
    { text: "The main thing is to keep the main thing the main thing.", author: "Stephen Covey" },
    { text: "When setting out on a journey, never seek advice from those who never left home.", author: "Unknown" },
    { text: "What is purpose to me? Purpose to me is simply being useful. I used to think I was put on Earth to be a wrestler. That was it. I was put on Earth to be a WWE Superstar. And then I started doing a little bit of acting and I'm like, 'It's easy. I'm a storyteller.' No. I am a human being. Breathing air like everybody else. And I'm significantly insignificant. I'm a grain of sand on a beach in a pale blue dot out in the middle of nowhere. I just wanna be useful. Life to me is a gift. And dude, I understand I have been given lottery ticket after lottery ticket after lottery ticket. I am lucky. I understand my luck and I try to live each day grateful for the luck. So, when the sun goes down, I look at what I did for the day, even if that's relaxed, 'Did I earn the sunset?' Some days I don't. And I motivate myself to try and do it again. But most days I do. And that's my sense of purpose. So, now I have what makes me happy. And I can chase those things and that's what makes the ride super fun.", author: "John Cena" },
    { text: "You don't have to be great to start, but you have to start to be great.", author: "Zig Ziglar" },
    { text: "The difference is you wear your watch to tell time, I wear my watch to tell you how valuable my time is.", author: "Unknown" },
    { text: "You have to be odd to be number one.", author: "Dr. Seuss" },
    { text: "Success comes to those who are too busy to be looking for it.", author: "Henry David Thoreau" },
    { text: "Twenty years from now you will be more disappointed by the things you didn't do than by the ones you did.", author: "Unknown" },
    { text: "The goal is to die with memories, not dreams.", author: "Unknown" },
    { text: "Grind in silence, let your achievements make the noise.", author: "Unknown" },
    { text: "The only place where success comes before work is in a dictionary.", author: "Vidal Sassoon" },
    { text: "If you want to buy without looking at the price, you got to work without looking at the clock.", author: "Warren Buffet" },
    { text: "If you put a king in the circus, the circus doesn't look like a palace. The king looks like a clown.", author: "Unknown" },
    { text: "I'd say one of the strongest mental frames that has gotten me through my hardest times is thinking, this is the story that I will one day tell. And that means, the harder it is, the bigger the dragon, the more epic the story, and by consequence, the more epic the hero. Winners define themselves by what they made happen. Losers define themselves by what happened to them.", author: "Alex Hormozi" },
    { text: "Sometimes you will never know the value of a moment until it becomes a memory.", author: "Theodor Seuss Geisel" },
    { text: "Be yourself; everyone else is already taken.", author: "Oscar Wilde" },
    { text: "Because you are a giver, make sure you don't fall in love with a taker. Cause a taker doesn't have limits, and neither does a giver.", author: "Unknown" },
    { text: "He who works all day has no time to make money.", author: "Unknown" },
    { text: "The early bird gets the worm, but the second mouse gets the cheese.", author: "Willie Nelson" },
    { text: "If you have the opportunity to play this game called life, you have to appreciate every moment. A lot of people don't appreciate their moment until it's passed.", author: "Kanye West" },
    { text: "Most of your friends aren't really your friends. They're just along for the ride when it's fun, convenient, or valuable. Your real friends are the ones who are there for you when it's none of those—when you have nothing to offer in return.", author: "Unknown" },
    { text: "I've learned that people will forget what you said, people will forget what you did, but people will never forget how you made them feel.", author: "Maya Angelou" },
    { text: "To a man with a hammer, everything looks like a nail.", author: "Unknown" },
    { text: "The best weight to lose is the weight of other people's opinions.", author: "Unknown" },
    { text: "Arguing with a fool proves there are two.", author: "Unknown" },
    { text: "Life is ironic. It takes sadness to know happiness, noise to appreciate silence, and absence value presence.", author: "Unknown" },
    { text: "No matter your age, you'll always wish you had started younger. But today is the youngest you'll ever be.", author: "Unknown" },
    { text: "As you get older, you realize that the quality of people in your life is more important than the number of people in your life.", author: "Unknown" },
    { text: "A bridge built on whispers will crumble beneath the weight of footsteps.", author: "Unknown" },
    { text: "Once you carry your own water, you will learn the value of every drop.", author: "Unknown" },
    { text: "If you're taught you can't do anything, you won't do anything. I was taught I could do everything.", author: "Unknown" },
    { text: "There is a limit to the time assigned to you, and if you don't use it to free yourself it will be gone and will never return.", author: "Marcus Aurelius" },
    { text: "If you went back and fixed all your mistakes, you would erase yourself.", author: "Unknown" },
    { text: "Worrying does not take away tomorrow's troubles, it takes away today's peace.", author: "Randy Armstrong" },
    { text: "You'll never find time for anything. If you want time, you must make it.", author: "Charles Buxton" },
    { text: "Fear is a mile wide and an inch deep.", author: "Alex Hormozi" },
    { text: "Don't lose sleep over cutting ties with someone who handed you the scissors.", author: "Unknown" },
    { text: "It's only about who stands in the rain with you when they had the choice to be dry.", author: "Unknown" },
    { text: "You realize, you don't miss playing the game as much as the way life felt when you were playing it.", author: "Unknown" },
    { text: "A person can have the whole bread and be jealous of your slice.", author: "Unknown" },
    { text: "Only dead fish follow the stream.", author: "Malcolm Muggeridge" },
    { text: "Lessons in life will be repeated until they are learned.", author: "Frank Sonnenberg" },
    { text: "The night opens its arms to those who carry a lamp, but swallows those who walk with bare hands.", author: "Unknown" },
    { text: "People who say it cannot be done should not interrupt those who are doing it.", author: "Unknown" },
    { text: "I finally found my rhythm when I realized that even the steps backwards were part of the dance.", author: "Unknown" },
    { text: "The warmest blankets have the coldest futures.", author: "Unknown" },
    { text: "A man who chases two rabbits catches neither.", author: "Unknown" },
    { text: "I've often said that I wish people could realize their dreams and wealth can be found, so that they can see that it's not where they're going to find their sense of completion.", author: "Unknown" },
    { text: "Never let the future disturb you. You will meet it, if you have to, with the same weapons of reason which today arm you against the present.", author: "Marcus Aurelius" },
    { text: "The quieter you become, the more you are able to hear.", author: "Unknown" },
    { text: "Retirement is when you stop sacrificing today for some imaginary tomorrow.", author: "Naval Ravikant" },
    { text: "If you think the price of winning is high, wait until you get the bill for regret.", author: "Unknown" },
    { text: "Don't waste your time with the opinions of fools who are only looking for others' faults and have neither the time nor ability to improve upon what you have created.", author: "Unknown" },
    { text: "The man who waits for the perfect conditions will stand still forever.", author: "Unknown" },
    { text: "You would give up everything you owned in 25 years to be the age and as healthy as you are right now.", author: "Unknown" },
    { text: "One day, in retrospect, the years of struggle will strike you as the most beautiful.", author: "Sigmund Freud" },
    { text: "Don't set yourself on fire to keep others warm.", author: "Unknown" },
    { text: "Expecting is the greatest impediment to living. In anticipation of tomorrow, it loses today.", author: "Seneca" },
    { text: "The problem is, you get more excited talking about it than you do when you're actually doing it.", author: "Unknown" },
    { text: "Your garden isn't thriving because every time a flower blooms, you cut it to prove to someone else that you're a gardener.", author: "Unknown" },
    { text: "Don't let getting lonely make you reconnect with toxic people. You shouldn't drink poison just because you're thirsty.", author: "Unknown" },
    { text: "Bees don't waste their time explaining to flies why honey is better than shit.", author: "Unknown" },
    { text: "Your future self is watching you through the memories you're making right now.", author: "Aubrey de Grey" },
    { text: "For every man that places his last block, there is a boy who places his first.", author: "Unknown" },
    { text: "Don't search for the exotic until you've discovered the basics.", author: "Unknown" },
    { text: "You don't drown by falling in the water, you drown by staying there.", author: "Edwin Louis Cole" },
    { text: "A habit missed once is a mistake. A habit missed twice is a start of a new habit.", author: "James Clear" },
    { text: "Everyone wants to be a soldier until they're faced with the reality of war.", author: "Unknown" },
    { text: "If you look at the people in your circle and don't get inspired, then you don't have a circle, you have a cage.", author: "Nipsey Hussle" },
    { text: "I have led a toothless life, he thought. A toothless life. I have never bitten into anything. I was waiting. I was reserving myself for later on and I have just noticed that my teeth have gone.", author: "Jean-Paul Sartre" },
    { text: "You've already achieved goals you said would make you happy. How can you presume that your happiness sits on the next side of the next set of goals given that right now you are on the other side of your last set of goals.", author: "Chris Williamson" },
    { text: "Have you ever watched kids on a merry-go-round, or listened to rain slapping the ground? Ever followed a butterfly's erratic flight, or gazed at the sun fading into the night? You better slow down, don't dance so fast, time is short, the music won't last. Do you run through each day on the fly, when you ask How are you?, do you hear the reply? When the day is done, do you lie in your bed, with the next hundred chores running through your head? You better slow down, don't dance so fast, time is short, the music won't last. Ever told your child, we'll do it tomorrow, and in your haste, not see his sorrow? Ever lost touch, let a friendship die, 'cause you never had time to call and say hi? You better slow down, don't dance so fast, time is short, the music won't last. When you run so fast to get somewhere, you miss half the fun of getting there. When you worry and hurry through your day, it's like an unopened gift thrown away. Life isn't a race, so take it slower, hear the music before your song is over.", author: "David L. Weatherford" },
    { text: "It is not the critic who counts: not the man who points out how the strong man stumbles or where the doer of deeds could have done better. The credit belongs to the man who is actually in the arena, whose face is marred by dust and sweat and blood, who strives valiantly, who errs and comes up short again and again, because there is no effort without error or shortcoming, but who knows the great enthusiasms, the great devotions, who spends himself in a worthy cause; who, at the best, knows, in the end, the triumph of high achievement, and who, at the worst, if he fails, at least he fails while daring greatly, so that his place shall never be with those cold and timid souls who knew neither victory nor defeat.", author: "Theodore Roosevelt" },
    { text: "People demand success but refuse to work weekends. People want opportunity but won't talk to strangers. People claim ambition but sleep in every day.", author: "Unknown" },
    { text: "We are the result of our actions, not our aspirations.", author: "Unknown" },
    { text: "Most people are willing to trade their entire lives, their dreams, their potential, their income, everything in order to not look stupid. In front of who? In front of a whole bunch of motherfuckers who aren't going to do anything in their entire lives?", author: "Unknown" },
    { text: "Watch your thoughts, they become your words. Watch your words, they become your actions. Watch your actions, they produce your future.", author: "Unknown" },
    { text: "Commitment means staying true to what you said you were going to do, long after the mood in which you said it has passed. Now ask yourself, are you committed?", author: "Inky Johnson" },
    { text: "The grape, once crushed, understands it will never be what it was. In that breaking, it becomes wine. The challenge of our lives is to turn our breaking into becoming, to let the crushing make something greater.", author: "Unknown" },
    { text: "There's someone out there who's way less qualified than you living the life you want. Simply because they took action.", author: "Unknown" },
    { text: "The next year is going to go by whether you're doing something about your life or not.", author: "Unknown" },
    { text: "People sit around dreaming, 'Someday I'm going to do this… Someday I'm going to get a different job…' Well, someday isn't a day of the week. Monday, Tuesday, Wednesday, Thursday, Friday, Saturday, Sunday. Someday isn't on there.", author: "Unknown" },
    { text: "Imagine you're on your deathbed and standing around your bed are the ghosts representing your unfulfilled potential. The ghosts of the ideas you never acted on. The ghosts of the talents you didn't use. And they're standing around your bed angry, disappointed and upset. 'We came to you because you could have brought us to life,' they say. 'And now we go to the grave together.' So I ask you today: How many ghosts are going to be around your bed when your time comes?", author: "Les Brown" },
    { text: "Fuck clubs. Fuck partying. Fuck trying to fit in and socialize, rub elbows with everybody, so people can stop calling you weird. Let me tell you something, all these clubs and parties ain't going nowhere, but the opportunity to get after it is.", author: "Unknown" },
    { text: "Every next level of your life will demand a different you.", author: "Leonardo DiCaprio" },
    { text: "Luck is what happens when preparation meets opportunity.", author: "Seneca" },
    { text: "Hard times create strong men. Strong men create good times. Good times create weak men. Weak men create hard times.", author: "G. Michael Hopf" },
    { text: "A lion doesn't concern himself with the opinion of sheep.", author: "Tywin Lannister" },
    { text: "The things you own end up owning you.", author: "Chuck Palahniuk" },
    { text: "Until you make the unconscious conscious, it will direct your life and you will call it fate.", author: "Carl Jung" },
    { text: "You will never change your life until you change something you do daily.", author: "John C. Maxwell" },
    { text: "The chains of habit are too light to be felt until they are too heavy to be broken.", author: "Warren Buffett" },
    { text: "A man who conquers himself is greater than one who conquers a thousand men in battle.", author: "Buddha" },
    { text: "Everybody wants to be a bodybuilder, but nobody wants to lift no heavy-ass weights.", author: "Ronnie Coleman" },
    { text: "The graveyard is the richest place on earth, because it is here that you will find all the hopes and dreams that were never fulfilled.", author: "Les Brown" },
    { text: "You miss 100% of the shots you don't take.", author: "Wayne Gretzky" },
    { text: "While you're waiting for your moment, moments are passing you by.", author: "Unknown" },
    { text: "Don't tell people your plans. Show them your results.", author: "Unknown" },
    { text: "If you are depressed, you are living in the past. If you are anxious, you are living in the future. If you are at peace, you are living in the present.", author: "Lao Tzu" },
    { text: "The world breaks everyone, and afterward, many are strong at the broken places.", author: "Ernest Hemingway" },
    { text: "Wealth is not about having a lot of money; it's about having a lot of options.", author: "Chris Rock" },
    { text: "You can't go back and change the beginning, but you can start where you are and change the ending.", author: "C.S. Lewis" },
    { text: "The two most important days in your life are the day you are born and the day you find out why.", author: "Mark Twain" },
    { text: "If you're the smartest person in the room, you're in the wrong room.", author: "Unknown" },

    // Philosophy & Stoicism
    { text: "The more we value things outside our control, the less control we have.", author: "Epictetus" },
    { text: "No man is free who is not master of himself.", author: "Epictetus" },
    { text: "Everything can be taken from a man but one thing: the last of the human freedoms — to choose one's attitude in any given set of circumstances, to choose one's own way.", author: "Viktor Frankl" },
    { text: "When we are no longer able to change a situation, we are challenged to change ourselves.", author: "Viktor Frankl" },
    { text: "Have patience with everything that remains unsolved in your heart. Try to love the questions themselves, like locked rooms and like books written in a foreign language. Do not now look for the answers. They cannot now be given to you because you could not live them. Live the questions now. Perhaps you will gradually, without even noticing it, find yourself experiencing the answer, some distant day.", author: "Rainer Maria Rilke" },
    { text: "Perhaps all the dragons in our lives are princesses who are only waiting to see us act, just once, with beauty and courage. Perhaps everything that frightens us is, in its deepest essence, something helpless that wants our love.", author: "Rainer Maria Rilke" },

    // Business & Entrepreneurship
    { text: "Forty hour workweeks are a relic of the Industrial Age. Knowledge workers function like athletes — train and sprint, then rest and reassess.", author: "Naval Ravikant" },
    { text: "What you do, and how you do it, is so much more important than how hard you do it.", author: "Naval Ravikant" },
    { text: "Desire is a contract that you make with yourself to be unhappy until you get what you want.", author: "Naval Ravikant" },
    { text: "The most contrarian thing of all is not to oppose the crowd but to think for yourself.", author: "Peter Thiel" },
    { text: "Every great business is built around a secret that's hidden from the outside. A great company is a conspiracy to change the world.", author: "Peter Thiel" },
    { text: "As long as you're over a certain threshold of intelligence, what matters most is determination.", author: "Paul Graham" },
    { text: "It is remarkable how much long-term advantage people like us have gotten by trying to be consistently not stupid, instead of trying to be very intelligent.", author: "Charlie Munger" },
    { text: "The first rule of compounding: never interrupt it unnecessarily.", author: "Charlie Munger" },
    { text: "Spend each day trying to be a little wiser than you were when you woke up. Discharge your duties faithfully and well. Slug it out one inch at a time, day by day.", author: "Charlie Munger" },

    // Discipline & Craft
    { text: "Pain is inevitable. Suffering is optional.", author: "Haruki Murakami" },
    { text: "Exerting yourself to the fullest within your individual limits: that's the essence of running, and a metaphor for life.", author: "Haruki Murakami" },
    { text: "In long-distance running the only opponent you have to beat is yourself, the way you used to be.", author: "Haruki Murakami" },
    { text: "You can only fight the way you practice.", author: "Miyamoto Musashi" },
    { text: "There is nothing outside of yourself that can ever enable you to get better, stronger, richer, quicker, or smarter. Everything is within.", author: "Miyamoto Musashi" },

    // Perspective & Wisdom
    { text: "Above all, don't lie to yourself. The man who lies to himself and listens to his own lie comes to a point that he cannot distinguish the truth within him, or around him, and so loses all respect for himself and for others.", author: "Fyodor Dostoevsky" },
    { text: "Taking a new step, uttering a new word, is what people fear most.", author: "Fyodor Dostoevsky" },
    { text: "Man has it all in his hands, and it all slips through his fingers from sheer cowardice.", author: "Fyodor Dostoevsky" },
    { text: "How much you truly believe in something can be manifested only through what you are willing to risk for it.", author: "Nassim Nicholas Taleb" },
    { text: "I'd rather be dumb and antifragile than extremely smart and fragile, any time.", author: "Nassim Nicholas Taleb" },

    // Literature & Writers
    { text: "An intellectual says a simple thing in a hard way. An artist says a hard thing in a simple way.", author: "Charles Bukowski" },
    { text: "The free soul is rare, but you know it when you see it — basically because you feel good, very good, when you are near or with them.", author: "Charles Bukowski" },
    { text: "You have to die a few times before you can really live.", author: "Charles Bukowski" },

    // Science
    { text: "You can know the name of a bird in all the languages of the world, but when you're finished, you'll know absolutely nothing whatever about the bird. So let's look at the bird and see what it's doing — that's what counts.", author: "Richard Feynman" },
    { text: "Fall in love with some activity, and do it. Nobody ever figures out what life is all about, and it doesn't matter. Explore the world. Nearly everything is really interesting if you go into it deeply enough.", author: "Richard Feynman" },

    // Historical
    { text: "Let the future tell the truth, and evaluate each one according to his work and accomplishments. The present is theirs; the future, for which I have really worked, is mine.", author: "Nikola Tesla" },
    { text: "It is paradoxical, yet true, to say that the more we know, the more ignorant we become in the absolute sense, for it is only through enlightenment that we become conscious of our limitations.", author: "Nikola Tesla" },
    { text: "When we understand that each day isn't one more, but one less, we'll start giving more value to the things that truly matter.", author: "Unknown" },
];

export function getQuoteOfTheDay(): Quote {
    // Determine day of year (0-365)
    const now = new Date();
    const start = new Date(now.getFullYear(), 0, 0);
    const diff = now.getTime() - start.getTime();
    const dayOfYear = Math.floor(diff / (1000 * 60 * 60 * 24));

    // Create a unique seed for the day (Year + Day)
    const seed = now.getFullYear() * 1000 + dayOfYear;

    // Simple pseudo-random generator using sine (deterministic for same seed)
    const random = Math.abs(Math.sin(seed) * 10000) % 1;

    // Select index based on seeded random
    const index = Math.floor(random * QUOTES.length);
    return QUOTES[index];
}

export function getRandomQuote(): Quote {
    const index = Math.floor(Math.random() * QUOTES.length);
    return QUOTES[index];
}